# Generated by Django 2.1.7 on 2022-09-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_001', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
