# Generated by Django 2.1.7 on 2022-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_001', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='男', max_length=2),
        ),
    ]
