# Generated by Django 3.2.15 on 2022-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_001', '0006_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('note', models.TextField(default='这家伙很懒，什么都没有介绍。')),
                ('gender', models.BinaryField(default=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
