# Generated by Django 3.2.15 on 2022-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_001', '0007_fieldtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtest',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fieldtest',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
