# Generated by Django 3.2.15 on 2022-09-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
