# Generated by Django 3.2.15 on 2022-09-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20220917_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogviews',
            name='view',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myblog.bloginfo'),
        ),
    ]
