# Generated by Django 3.2.15 on 2022-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20220917_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogviews',
            name='view',
        ),
        migrations.DeleteModel(
            name='BlogInfo',
        ),
        migrations.DeleteModel(
            name='BlogViews',
        ),
    ]
