# Generated by Django 3.2.15 on 2022-09-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_bloginfo_blogviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogViews',
        ),
    ]
