# Generated by Django 3.2.15 on 2022-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_delete_blogviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogInfo',
        ),
    ]
