# Generated by Django 3.2.15 on 2022-09-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_bloginfo_blogviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogviews',
            name='view',
        ),
        migrations.DeleteModel(
            name='BlogInfo',
        ),
        migrations.DeleteModel(
            name='BlogViews',
        ),
    ]
