# Generated by Django 3.2.15 on 2022-09-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('a_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_002.academy')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=True)),
                ('stu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db_002.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('str_course', models.ManyToManyField(to='db_002.Student')),
            ],
        ),
    ]
