# Generated by Django 3.2.15 on 2022-09-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='str_course',
            new_name='stu_course',
        ),
    ]
