# Generated by Django 3.2.15 on 2022-09-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0002_rename_str_course_course_stu_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stu_course',
            new_name='stu',
        ),
    ]
