# Generated by Django 3.2.15 on 2022-09-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0003_rename_stu_course_course_stu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='s_id',
            new_name='a_id',
        ),
    ]
