# Generated by Django 3.2.15 on 2022-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0004_rename_s_id_academy_a_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='a_id',
            new_name='a',
        ),
    ]
