# Generated by Django 3.2.15 on 2022-09-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0008_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pwd',
        ),
    ]
