# Generated by Django 3.2.15 on 2022-09-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_002', '0009_auto_20220923_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
